name: assign issues automatically

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign Issue'
        uses: pozil/auto-assign-issue@v1.12.0
        with:
          assignees: annemayor, wooooooood, deveeni
          
